config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  devise_scope :user do
    authenticated :user do
      root 'projects#index'
    end
    unauthenticated :user do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :users do
    resources :projects do
      resources :issues
    end
  end

  resources :users do
    resources :issues
  end

  authenticate :user do
    resources :users do
      resources :issues
    end
  end

  authenticate :user do
    resources :projects
    resources :issues
  end

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :project
  has_one :user, :through => :project
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_project
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    # @issues = Issue.all
    # @issues = @project.issues.all

    # This shows only the issues belonging to projects belonging to the current user.

    @issues = Issue.order(risk_level: :desc).joins(:project).where('projects.user_id': current_user.id)

    # @issues = Issue.joins(:project).where('projects.user_id': current_user.id)
    #
    @project = @project
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    # @issue = Issue.new
    @issue = @project.issues.build
    @user = current_user
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params['id'])
    @user = current_user
  end

  # POST /issues
  # POST /issues.json
  def create
    # @issue = Issue.new(issue_params)
    @issue = @project.issues.build(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

  def set_user
    @user = current_user
  end

  def set_issue
    @issue = Issue.find(params[:id])
  end

  def set_project
    if params[:project_id]
      @project = @user.projects.find(params[:project_id])
    else
      @message = "You have no issues. Good news indeed."
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.

  def issue_params
  params.require(:issue).permit(:item, :function, :failure, :effect_of_failure, :cause_of_failure, :current_controls, :recommended_actions, :probability_estimate, :severity_estimate, :detection_indicators, :detection_dormancy_period, :risk_level, :further_investigation, :project_id)
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for([@user, @project, @issue]) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if false %>
  <h2>Project name is: <%= @project.name %> </h2>

  <% end %>

  <h3>Project owner is: <%= @user.firstname %> <%= @user.lastname %></h3>

  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :function %><br>
    <%= f.text_field :function %>
  </div>
  <div class="field">
    <%= f.label :failure %><br>
    <%= f.text_field :failure %>
  </div>
  <div class="field">
    <%= f.label :effect_of_failure %><br>
    <%= f.text_field :effect_of_failure %>
  </div>
  <div class="field">
    <%= f.label :cause_of_failure %><br>
    <%= f.text_field :cause_of_failure %>
  </div>
  <div class="field">
    <%= f.label :current_controls %><br>
    <%= f.text_field :current_controls %>
  </div>
  <div class="field">
    <%= f.label :recommended_actions %><br>
    <%= f.text_field :recommended_actions %>
  </div>
  <div class="field">
    <%= f.label :probability_estimate %><br>
    <%= f.number_field :probability_estimate %>
  </div>
  <div class="field">
    <%= f.label :severity_estimate %><br>
    <%= f.number_field :severity_estimate %>
  </div>
  <div class="field">
    <%= f.label :detection_indicators %><br>
    <%= f.number_field :detection_indicators %>
  </div>
  <div class="field">
    <%= f.label :detection_dormancy_period %><br>
    <%= f.number_field :detection_dormancy_period %>
  </div>
  <div class="field">
    <%= f.label :risk_level %><br>
    <%= f.number_field :risk_level %>
  </div>
  <div class="field">
    <%= f.label :further_investigation %><br>
    <%= f.text_field :further_investigation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Function</th>
      <th>Failure</th>
      <th>Effect of failure</th>
      <th>Cause of failure</th>
      <th>Current controls</th>
      <th>Recommended actions</th>
      <th>Probability estimate</th>
      <th>Severity estimate</th>
      <th>Detection indicators</th>
      <th>Detection dormancy period</th>
      <th>Risk level</th>
      <th>Further investigation</th>
      <th>Project ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.item %></td>
        <td><%= issue.function %></td>
        <td><%= issue.failure %></td>
        <td><%= issue.effect_of_failure %></td>
        <td><%= issue.cause_of_failure %></td>
        <td><%= issue.current_controls %></td>
        <td><%= issue.recommended_actions %></td>
        <td><%= issue.probability_estimate %></td>
        <td><%= issue.severity_estimate %></td>
        <td><%= issue.detection_indicators %></td>
        <td><%= issue.detection_dormancy_period %></td>
        <td><%= issue.risk_level %></td>
        <td><%= issue.further_investigation %></td>
        <td><%= issue.project_id %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if false %>
<%= link_to 'New Issue', new_project_issue_path(:project_id => @project.id) %>
<% end %>

app/views/issues/new.html.erb
<h1>Report a new issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @issue.item %>
</p>

<p>
  <strong>Function:</strong>
  <%= @issue.function %>
</p>

<p>
  <strong>Failure:</strong>
  <%= @issue.failure %>
</p>

<p>
  <strong>Effect of failure:</strong>
  <%= @issue.effect_of_failure %>
</p>

<p>
  <strong>Cause of failure:</strong>
  <%= @issue.cause_of_failure %>
</p>

<p>
  <strong>Current controls:</strong>
  <%= @issue.current_controls %>
</p>

<p>
  <strong>Recommended actions:</strong>
  <%= @issue.recommended_actions %>
</p>

<p>
  <strong>Probability estimate:</strong>
  <%= @issue.probability_estimate %>
</p>

<p>
  <strong>Severity estimate:</strong>
  <%= @issue.severity_estimate %>
</p>

<p>
  <strong>Detection indicators:</strong>
  <%= @issue.detection_indicators %>
</p>

<p>
  <strong>Detection dormancy period:</strong>
  <%= @issue.detection_dormancy_period %>
</p>

<p>
  <strong>Risk level:</strong>
  <%= @issue.risk_level %>
</p>

<p>
  <strong>Further investigation:</strong>
  <%= @issue.further_investigation %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>