config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  devise_scope :user do
    authenticated :user do
      root 'projects#index'
    end
    unauthenticated :user do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :users do
    resources :projects do
      resources :issues
    end
  end

  resources :users do
    resources :issues
  end

  authenticate :user do
    resources :users do
      resources :issues
    end
  end

  authenticate :user do
    resources :projects
    resources :issues
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :issues
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_user
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    # @projects = Project.all
    if @user

      @projects = @user.projects
      @users = User.all

      @users.each do |u_name|
        puts "User's name is #{u_name.firstname} #{u_name.lastname}"
        puts @users
      end

      @projects.each do |proj|
        puts 'Project name is ' + proj.name
        puts 'Project user ID is ' + proj.user_id.to_s

        @user_name = @users.find(proj.user_id).firstname + " " + @users.find(proj.user_id).lastname
        puts "User name is " + @user_name.to_s
        puts
      end

      @all_users = User.all

      @all_users.each do |user|
        puts user
      end
    end


  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @users = User.all
    @project = @user.projects.build
  end

  # GET /projects/1/edit
  def edit
    @users = User.all
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = @user.projects.build(project_params)
    # @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    def set_project
      @project = @user.projects.find(params[:id])
      # @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Owner of project is: <%= current_user.firstname %> <%= current_user.lastname %></h2>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%= f.hidden_field :user_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Projects</h1>

<table>
  <% if @projects %>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% else %>
    <h2>You don't have any projects yet</h2>
    <% end %>
  </tbody>
</table>

<br>



<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>Create a new project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<% if false %>
<%= link_to 'You need to create some issues in your project', new_project_issue_path(@project) %>

<% end %>

<%= link_to "Create a new issue for your project", new_user_project_issue_path(:project_id => @project.id, :user_id => @user.id)%>



<hr>

<%= link_to 'Back', projects_path %>